backend:
  name: github #OK
  repo: rustamnew/vuepress_netlify_test #OK
  branch: main #OK
media_folder: "docs/.vuepress/public/images/"
public_folder: "docs/.vuepress/dist/"
publish_mode: editorial_workflow #OK

collections:
  - name: "manual" #OK # Used in routes, e.g., /admin/collections/blog
    label: "manual" #OK # Used in the UI
    folder: "docs/manual/" # The path to the folder where the documents are stored
    create: true #OK # Allow users to create new documents in this collection
    slug: "{{slug}}" #OK # Filename template, e.g., YYYY-MM-DD-title.md
    show_preview_links: true
    fields: #OK # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "heroImage", widget: "image", required: false}
